/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VimbaWrap */

#ifndef _Included_VimbaWrap
#define _Included_VimbaWrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VimbaWrap
 * Method:    Initialize
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_VimbaWrap_Initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     VimbaWrap
 * Method:    Snap
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jboolean JNICALL Java_VimbaWrap_Snap
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     VimbaWrap
 * Method:    Realese
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_VimbaWrap_Realese
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
